### PR TITLE
Add `user_mod` syntax and a few fixups

### PR DESCRIPTION
**Pull request by blag**
* ~~Convert indentation to spaces and~~ use Unix line endings
* PEP8 fixups (ignoring line too long errors)
* Extend the syntax to allow classes to pass-through without being prefixed
* Add tests for syntax extension and `prefix_base_pairs` setting

All tests pass.

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@blag I prefer tabs and would rather keep it that way. It also makes it hard to see the actual code changes that happened here.

### `user_mod`

```
&icon-namehere::red; and with multiple "&icon-spinner::red,bold;
```

```
<i aria-hidden="true" class="icon-namehere red"></i> and with multiple <i aria-hidden="true" class="icon-spinner red bold"></i>
```

Does it work with both `mod` and `user_mod` at the same time? `&icon-spinner:spin::red;`

**Comment by blag** [comment]
I will push another commit to convert it back to tabs shortly.

Yes, users can specify `mod` and `user_mod` at the same time, however the syntax is simply:

```
&<prefix>-<name>:<mod>:<user_mod>;
```

(you had a double colon between the `mod` and the `user_mod` when there shouldn't be one).


So this:

```
&fa-spinner:2x,spin:red,bold;
```

will be converted to:

```
<i aria-hidden="true" class="fa fa-spinner fa-2x fa-spin red bold"></i>
```

and this:

```
&fa-spinner::red,bold;
```

doesn't have any `mod`s but it does have `user_mod`s, so it will convert to just:

```
<i aria-hidden="true" class="fa fa-spinner red bold"></i>
```

All of these examples assume `prefix="fa-"` and `base="fa"`.

Does that syntax make sense?

**Comment by blag** [comment]
Sorry for the noise - trying to figure out how to make another branch prepping for PyPI release.

**Comment by blag** [comment]
Any update on this?

**Comment by MadLittleMods** [comment]
@blag I plan to review over the weekend.

**Comment by MadLittleMods** [comment]
It has been a while since I have played with the `markdown` pacakge and python.

Following the [instructions I wrote previously](https://github.com/blag/markdown-icons#how-to-run-the-unit-tests), I am getting `ImportError: Failed loading extension 'iconfonts' from 'iconfonts', 'markdown.extensions.iconfonts' or 'mdx_iconfonts'`

@blag Mind hopping on [Gitter](https://gitter.im/) to chat?

**Comment by blag** [comment]
Currently busy, will be done in ~15 minutes, then sure! :)

**Comment by blag** [comment]
Now in Gitter room with you if you want to chat.

Ensure that `iconfonts.py` is in your Python path (not necessarily in site-packages/markdown/extensions) and markdown should pick it up.

**Comment by MadLittleMods** [comment]
The code in master works just fine.

Copying in your PR `iconfonts.py` and running the tests results in the plugin not found error:
> Failed loading extension 'iconfonts' from 'iconfonts', 'markdown.extensions.iconfonts' or 'mdx_iconfonts'

**Comment by blag** [comment]
Added installing six to instructions - tests now pass in brand new virtualenv when following installation instructions.

**Comment by MadLittleMods** [comment]
@blag Can we avoid using `six`? Making this as simple as possible to use and install (copy-paste) would be ideal.

**Comment by blag** [comment]
Sure do you want to support Python 2 or Python 3?

I'd recommend using `six` if you want both because that's the entire point of that library.

**Comment by blag** [comment]
Updated PR to use `dict.items()`, which returns a list on Python 2 (which is slower) and an iterator on Python 3 (which is faster).

Removed `six` from the `README.md` as well.

This PR should be set to jet. :smile:

**Comment by MadLittleMods** [comment]
@blag Awesome, I'll test it soon. Is it working for you without adding to the path?

**Comment by blag** [comment]
Yes, everything is working fine for me.

**Comment by blag** [comment]
How is your testing going?

**Comment by MadLittleMods** [comment]
@blag As you can tell, I haven't been testing for 28 days. Sorry for not getting to this sooner.

**Comment by blag** [comment]
No worries, I just wanted to drop a friendly reminder. :smiley:

**Comment by MadLittleMods** [comment]
@blag Looks good, Clean up the commit history and squash into a single commit "Add `user_mod` option for non-prefixed classes"

**Comment by blag** [comment]
Good to hear it's working for you. :)

Are you telling me to clean up the commit history and squash it into a single commit?

**Comment by MadLittleMods** [comment]
I was but oh well, this has been sitting for too long.

**Pull request merged**
